In [1]:
import os
import glob
import pandas as pd
from pandas import Series, DataFrame
from dataset import Dataset
from params import get_params

In [2]:
params = get_params()
dataset = Dataset(params)
df = dataset._get_data()

In [3]:
df.shape

(8933681, 28)

In [4]:
df

,nom_c,edad_c,edad,causa_bas,nac_dia,base,nac_mes,nac_anio,sexo,afiliacion,...,def_mun,def_sitio,def_dia,def_mes,def_anio,cert_por,cert_ced,cert_nom,num_acta,informante
0,DESCONOCIDO DESCONOCIDO DESCONOCIDO,0,888,R99X,88,2016,88,8888,1,0,...,17006,1,29,4,2016,2,1696218,PEDRO ALBERTO VAZQUEZ VALLEJO,88888,NO ESPECIFICADO NO ESPECIFICADO NO ESPECIFICADO
1,DESCONOCIDO DESCONOCIDO DESCONOCIDO,0,888,X958,88,2016,88,8888,0,0,...,32042,12,3,3,2016,2,7294240,ISELA JANET ORTEGA GOMEZ,00941,LIC JOSE ANGEL GARCIA GARCIA
2,DESCONOCIDO DESCONOCIDO DESCONOCIDO,0,888,Y097,88,2016,88,8888,0,0,...,32037,12,99,99,9999,2,8468114,DRA JARED GARCIA BARAJAS,01060,NO ESPECIFICADO NO ESPECIFICADO NO ESPECIFICADO
3,VAZQUEZ RODRIGUEZ ELDA MARIA,0,888,K830,21,2016,5,1930,2,99,...,31050,9,5,9,2016,1,6804984,MARIO ARTURO PENICHE PAVIA,05832,RICARDO ALFONSO BRICEÃ‘O VAZQUEZ
4,DESCONOCIDO DESCONOCIDO DESCONOCIDO,0,888,K746,88,2016,88,8888,1,99,...,15106,1,17,3,2016,2,1042138,JORGE RICARDO ARREOLA VILLARREAL,01167,KARINA BETZABEL SALGADO VAZQUEZ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
606162,DESCONOCIDO DESCONOCIDO DESCONOCIDO,9,999,Y349,99,2013,99,9999,1,0,...,7000,1,10,3,2013,2,5357703,ANA LORENA HERNANDEZ SALAZAR,00043,NO ESPECIFICADO NO ESPECIFICADO NO ESPECIFICADO
606163,DESCONOCIDO DESCONOCIDO DESCONOCIDO,9,999,V099,99,2013,99,9999,1,0,...,13069,10,19,1,2013,2,2629519,AIDE GUTIERREZ VAZQUEZ,00039,CRISTOBAL TORRES BUTRON
606164,ALCARAZ NO ESPECIFICADO N.N. O CARLOS,9,999,W190,99,2013,99,9999,1,99,...,14067,11,4,3,2013,2,6335701,ALBERTO RAMOS MELENDEZ,00627,NO ESPECIFICADO NO ESPECIFICADO NO ESPECIFICADO
606165,SE IGNORA SE IGNORA NO IDENTIFICADO,9,999,Y349,99,2013,99,9999,1,99,...,18017,10,3,3,2013,2,5782781,MARCELA MURO GARCIA,-,SE IGNORA SE IGNORA SE IGNORA
606166,ONTIVEROS COBOS JESUS,9,999,N391,99,2013,99,9999,1,2,...,8032,3,4,9,2013,3,5097548,ANGELES ALI AGUILAR LOPEZ,00791,ELIGIO ONTIVEROS LOPEZ

In [5]:
df.groupby('edo_civil')['base'].value_counts()

edo_civil  base
0          2021    35396
           2017    15618
           2020    15382
           2022    13076
           2016    12084
                   ...
9          2013    15626
           2014    14800
           2022    13623
           2011    12249
           2010     9477
Name: base, Length: 111, dtype: int64